### ISSUE TITLE
Кепки и некоторая одежда в лоадауте криво сидит на женских персонажах

### ISSUE THREAD

**Issue by Artemonim** [NuPhase/NuclearPhase#105]
### Проблема
Кепки и некоторая одежда в лоадауте криво сидит на женских персонажах

---
[из Discord](https://discord.com/channels/1056493871070187540/1063212133665472563/1127619348601778186)

**Comment by Pl3aseJust3ndMySuffering** [comment]
'Некоторую одежду' теперь записываем как индивидуальные коммиты для каждого типа одежды.
