### ISSUE TITLE
Перенос вещей игроков с прошлого раунда

### ISSUE THREAD

**Issue by Artemonim** [NuPhase/NuclearPhase#117]
### Решение
- Добавить переносимым объектам флаг "был тронут игроком";
- Раундстартом у всего на карте он FALSE;
- Если какой-либо игрок как-либо перемещал этот объект - флаг становится TRUE;
- По завершению раунда с шансом 5% объект, его координаты и состояние запоминаются в кэш сервера;
- Раундстартом на карту добавляются объекты, что были сохранены в кэше.

Добавит хаоса, но может привести и к интересным ситуациям.
Также можно распространить на грязь и прочий мусор.

---
[из Discord](https://discord.com/channels/1056493871070187540/1063212133665472563/1135193613593227264), поддержано двумя эмоджи

**Comment by Pl3aseJust3ndMySuffering** [comment]
Реализовано.
