### ISSUE TITLE
Автоматический режим экстренного охлаждения в атмосферном контроллере

### ISSUE THREAD

**Issue by Artemonim** [NuPhase/NuclearPhase#143]
### Проблема
Необходимо доработать функционал атмосферного контроллера, добавив автоматический режим экстренного охлаждения.

### Решение
1. При достижении температуры в отсеке +80°C и выше, контроллер активирует сирену.
2. Через 10-30 секунд после активации сирены пожарные створки автоматически закрываются (рассмотреть возможность закрытия на болты для усиления безопасности).
3. Активируется встроенная система охлаждения в контроллере.
4. Скруберы начинают активное удаление кислорода из отсека, одновременно стараясь поддерживать давление на уровне 1 атмосферы.
5. Вентиляция наполняет комнату азотом для быстрого охлаждения.

Режим будет автоматически активен до момента ручного отключения или пока температура в отсеке не снизится до уровня 30-40°C. После этого стандартный режим фильтрации включится автоматически, обеспечив очистку воздуха от примесей и стабилизацию давления.

Данная фича будет особенно полезна для предотвращения пожарных ситуаций и для будущих антагонистов, желающих создать экстремальные условия на станции.

---
[из Discord](https://discord.com/channels/1056493871070187540/1063212133665472563/1154375805279944784)

**Comment by Pl3aseJust3ndMySuffering** [comment]
Уже реализовано.
