### ISSUE TITLE
Размеры спрайтов нижнего белья не согласованы со спрайтами одежды

### ISSUE THREAD

**Issue by Artemonim** [NuPhase/NuclearPhase#70]
### Проблема
Переместите красные трусы внутрь серых штанов
![Скриншот](https://media.discordapp.net/attachments/1063212133665472563/1094667424076398662/2023-04-09_17-06-46.png)

---
[из Discord](https://discord.com/channels/1056493871070187540/1063212133665472563/1094667424290328687)

**Comment by Pl3aseJust3ndMySuffering** [comment]
'Некоторую одежду' теперь записываем как индивидуальные коммиты для каждого типа одежды.
