### ISSUE TITLE
Улучшить читаемость описания повреждений куклы

### ISSUE THREAD

**Issue by Artemonim** [NuPhase/NuclearPhase#71]
### Проблема
![скриншот](https://media.discordapp.net/attachments/1063212133665472563/1094667575285272756/2023-04-09_18-13-24.png)

---
[из Discord](https://discord.com/channels/1056493871070187540/1063212133665472563/1094667575482388480)

**Comment by Pl3aseJust3ndMySuffering** [comment]
Уже реализовано.
